version: '3'
services:
  portfolio:
    container_name: portfolio
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/portfolio
    ports:
      - "3000:3000"
    depends_on:
      - database

  database:
    container_name: postgres
    image: postgres:10-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
    volumes:
      - .:/portfolio_db
    ports:
      - "5432:5432"
