version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.12.0
    working_directory: ~/workspace

    steps:
      - checkout
      - restore_cache:
          key: yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: install dependencies
          command: yarn install
      - run:
          # NOTE: Added a command to avoid build failures
          # Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 8.x
          name: rebuild node-sass
          command: yarn add node-sass --force

      # ビルド実行
      - run:
          name: build
          command: yarn export
      - save_cache:
          key: yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/workspace/node_modules
      # ビルドした結果をdeployジョブでも利用するために一時保存
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    docker:
      - image: circleci/node:8.12.0
    working_directory: ~/workspace

    steps:
      # buildジョブで一時保存されたビルド結果を読み込む
      - attach_workspace:
          at: .
      - run:
          name: install firebase
          command: yarn add firebase-tools
      - run:
          # Firebaseへデプロイ
          name: deploy to firebase
          command: node_modules/.bin/firebase deploy --only hosting --project "$FIREBASE_PJ" --token "$FIREBASE_TOKEN"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          # masterブランチのコミットのみデプロイ
          filters:
            branches:
              only: master
